application: sandeva
version: 17
runtime: python
api_version: 1
threadsafe: no

#libraries:
#- name: django
#  version: "1.3"

#builtins:
#- django_wsgi: on

#env_variables:
#  DJANGO_SETTINGS_MODULE: 'settings'

handlers:
- url: /static
  static_dir: static

- url: /testpdf
  script: testpdf.py

- url: /srishell/download/.*
  script: blob.py

- url: /(google827b06f69a5ea5a6\.html)
  static_files: static/\1
  upload: static/(.*)
  
- url: /.*
  script: main.py


